### ISSUE TITLE
Add new chains support in creating raw transaction based on type 1 or type 2 transaction support on individual chains

### ISSUE THREAD

**Issue by ananyavasudeva** [getsafle/safle-keyless-js#54]
Add new chains support in creating raw transaction based on type 1 or type 2 transaction support on individual chains

- Bcs
- Velas
- Mantle
- Optimism
- Arbitrum

**Comment by SDargarh** [comment]
Related PR, change implemented
https://github.com/getsafle/safle-keyless-js/pull/56
