### ISSUE TITLE
Widget is opening only when CORS extension is ON

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#80]
Steps to reproduce:
1.Open demo app
2.Try to connect without switching on the CORS extension

Actual result:
Widget is opening only when CORS extension is ON

https://github.com/getsafle/safle-keyless-js/assets/149378074/c04b3573-5157-445a-ad4f-bbbf7af43930

Expected result:
Widget should be working fine if CORS is off

**Comment by sshubhamagg** [comment]
Closed by merging [PR](https://github.com/getsafle/safle-keyless-core/pull/42)

**Comment by mohancool94** [comment]
Now the issue is fixed on test env

https://github.com/getsafle/safle-keyless-js/assets/149378074/e23182c9-a535-4fad-8a35-d2d446a3cb8b
