### ISSUE TITLE
Chain icon needs to be unique for all the chains and wallets on chain /wallets dropdown

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#83]
Steps to reproduce:
1.Open demo app
2.connect and sign in 
3.Then check the chain and wallet icons

Actual result:
Chain icon and wallet icon is looking same for all the chains and wallets

![Image](https://github.com/getsafle/safle-keyless-js/assets/149378074/9339bd9f-9455-4b70-9708-c69d3a5d583d)

Expected result:
Chain icon and wallet icons should be unique

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/8a19e90a-d428-4203-8c55-c1df9f5bdadf



Issue is fixed on drop down
But when the chain is selected ...its showing one chain icon for all the chains

**Comment by surajsingla333** [comment]
Fixed.
https://drive.google.com/file/d/1kQUA65cySuHTLrLVQwZQChKkMz9rc6B3/view?usp=sharing

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/85ca927b-c17b-4bdb-9586-39f7b8ee9679

Issue if fixed now
