### ISSUE TITLE
Rejection from confirmation popup closes the widget instead of navigating to dashboard or chain/wallet selection screen

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#85]
Steps to reproduce:
1.Open demo app
2.Connect and login to safle id
3.Try to cancel the transaction from pin screen or confirmation popup

Actual result:
Rejection from confirmation popup closes the widget instead of navigating to dashboard or chain/wallet selection screen

https://github.com/getsafle/safle-keyless-js/assets/149378074/f44612af-05fd-4029-90e7-4197b75102a8

Expected result:
Need to navigate the user to dashboard or chain/wallet selection screen if user cancels the transaction from confirmation popop and pin verification popup

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/134ea6bf-0e6d-476b-a5db-977f2a1af3ae

Widget is fully closed upon rejecting the transaction from confirmation popup

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/00a495da-cc8a-4989-b872-6bb3aa538f5e

Not fixed

**Comment by surajsingla333** [comment]
https://drive.google.com/file/d/1YM3bkJCyfP2giE3kWARstCXYlRfIqKtc/view?usp=sharing
Fixed

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/64fc8179-cf32-4754-bf5d-522e30ce1b1d

still able to replicate the issue

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/d5d74a36-c02b-4d9f-a226-57ec3cdcaf11

still able to replicate this issue @surajsingla333

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/5dc747a6-bcb5-42d5-b988-d6a1f64b82d1

Fixed
