### ISSUE TITLE
"d.decriptionKey.reduce is not a function " Getting this error when widget is connected automatically after reload

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#90]
Steps to reproduce:
    
    1.Connect wallet
    2.Sign in to safle user
    3.Then do a transaction on new chains
    4.Complete the transaction
    5.Widget will be autoclosed
    6.Then try to reload the demo app link
    7.Connect again and do a transaction

Actual result:
"d.decriptionKey.reduce is not a function " Getting this error when widget is connected automatically after reload

https://github.com/getsafle/safle-keyless-js/assets/149378074/0e2e1a79-af19-45c9-b232-bc37d15b0ca8

Expected result:
Transactions should be working fine even after reloading and connecting the widget

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/7e5971a4-92d8-4aad-b704-d3a54864b58c

Issue still exist

**Comment by mohancool94** [comment]
Uploading 14.11.2023_18.46.17_REC.mp4…
Not fixed

**Comment by surajsingla333** [comment]
The accounts will not connect automatically now.

**Comment by mohancool94** [comment]
![Screenshot_1770](https://github.com/getsafle/safle-keyless-js/assets/149378074/41a1f74a-6276-4fbe-b558-10cada5e2586)
Still able to reconnect automatically and getting this error

**Comment by mohancool94** [comment]
https://github.com/getsafle/safle-keyless-js/assets/149378074/edb57543-5cfc-4f73-a393-b0cd23fe54a4

Fixed now
