### ISSUE TITLE
Widget is disconnected if user clicks on x button after signing in without choosing chain and wallet

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#95]
Steps to reproduce:
1.Open demo app
2.Click on connect and sign in with any user
3.Click on x button from wallet/chain selection screen and observe

Actual result:
Widget is disconnected if user clicks on x button directly after signing in without choosing chain and wallet

https://github.com/getsafle/safle-keyless-js/assets/149378074/c6442c5b-f02f-4268-b6f0-e2d135a986e2

Expected result:
X button should only close the widget
It should not disconnect the widget

**Comment by surajsingla333** [comment]
This is not a bug. If the chain is not selected then the user won't be logged in as keyless and will not know which network to work on.

**Comment by mohancool94** [comment]
Closing as per the above comment
