### ISSUE TITLE
Unable to sign in to widget using valid email id and password

### ISSUE THREAD

**Issue by mohancool94** [getsafle/safle-keyless-js#96]
Unable to sign in to widget using valid email id and password

Steps to reproduce:
1.Open demo app
2.Click on connect
3.Then enter valid email and valid password
4.Check whether the user is allowed to signin

Actual result:

Unable to sign in to widget using valid email id and password

![Image](https://github.com/getsafle/safle-keyless-js/assets/149378074/b15a89dd-10e7-4bfb-844b-2c05d7584935)

Expected result:
User must be allowed to sign with email id

**Comment by surajsingla333** [comment]
In keyless, only signin with safleId is there. 
This was discussed earlier as we will need captcha response for signing in using email and we don't have recaptcha widget in keyless.

**Comment by mohancool94** [comment]
Closing this issue since we have only signin with safle id option for  now
![Screenshot_1769](https://github.com/getsafle/safle-keyless-js/assets/149378074/16c537cf-249e-4ea4-bd27-afb989c807fb)
